import type { PartyKey } from '@/theme/colors';

/**
 * Top-Trump score axis. All normalised 0..100 relative to dataset maximum.
 * knoxFactor = simple average of the other four axes.
 */
export interface TopTrumpScores {
  views:       number;   // 0..100  normalised avg post views
  frequency:   number;   // 0..100  normalised posting frequency (posts today)
  engagement:  number;   // 0..100  normalised (likes + comments + shares) / views rate
  followers:   number;   // 0..100  normalised total follower count
  knoxFactor:  number;   // 0..100  average of the four axes above
}

export type ScoreKey = keyof TopTrumpScores;

export interface RecentPost {
  postId:    string;
  caption:   string;
  views:     number;
  likes:     number;
  summary?:  string;    // AI-generated summary from n8n / Gemini
  style?:    string;
  topic?:    string;
  coverJpeg?: string;
  videoMp4?:  string;
  postUrl?:   string;
  postDate?:  string;
}

/** Full post record used by the PostsTable section. */
export interface PostRecord {
  postId:          string;
  profile:         string;
  politicianName:  string;
  partyKey:        import('@/theme/colors').PartyKey;
  caption:         string;
  videoSummary:    string;
  coverJpeg:       string;
  videoMp4:        string;
  postUrl:         string;
  postDate:        string;
  style:           string;
  topics:          string[];
  views:           number;
  likes:           number;
  comments:        number;
  shares:          number;
  saves:           number;
}

/**
 * Statistical distribution benchmarks for a metric across the full post dataset.
 * Used to render box-and-whisker plots per post.
 */
export interface MetricBenchmark {
  min:    number;
  p25:    number;
  median: number;
  mean:   number;
  p75:    number;
  max:    number;
}

/** Weekly briefing generated by Gemini — returned by /api/brief */
export interface BriefResponse {
  narrative: string;
  insights:  Array<{ headline: string; body: string }>;
}

export interface PostBenchmarks {
  views:      MetricBenchmark;
  engagement: MetricBenchmark;  // (likes + comments + shares) / views × 100
}

export interface Politician {
  id: string;
  name: string;
  handle: string;           // e.g. "@rishisunak"
  role: string;             // e.g. "MP, Richmond"
  partyKey: PartyKey;
  partyLabel: string;       // human-readable party name
  country: string;          // ISO-style short e.g. "UK"
  avatarInitials: string;   // two-letter fallback
  totals: {
    posts:          number;
    followers:      number;
    followerChange: number | null;  // daily delta — positive = growth
    likes:          number;
    views24h:       number;
    likesToday:     number;
    commentsToday:  number;
    savesToday:     number;
    postsToday:     number;
    postsThisWeek:  number;
  };
  scores: TopTrumpScores;
  recentPosts: RecentPost[];
}
