import type { PartyKey } from '@/theme/colors';

/**
 * Top-Trump score axis. All normalised 0..100 relative to dataset maximum.
 * knoxFactor = weighted composite of the four axes, then compressed around 50
 *              via the Moz-DA-style curve in data/knoxConfig.ts.
 */
export interface TopTrumpScores {
  views:       number;   // 0..100  normalised avg post views
  frequency:   number;   // 0..100  normalised posting frequency (posts today)
  engagement:  number;   // 0..100  normalised (likes + comments + saves + shares) / views rate
  followers:   number;   // 0..100  normalised total follower count
  knoxFactor:  number;   // 0..100  weighted + curve-compressed composite (see knoxConfig.ts)
}

export type ScoreKey = keyof TopTrumpScores;

// ── Account page types ────────────────────────────────────────────────────────

/** A single entry in a per-metric leaderboard. */
export interface AccountRankEntry {
  id:             string;
  name:           string;
  handle:         string;
  partyKey:       PartyKey;
  avatarUrl?:     string;
  avatarInitials: string;
  score:          number;
}

/** Ranking data for one score metric on an account page. */
export interface AccountRanking {
  rank:         number;
  total:        number;
  top5:         AccountRankEntry[];
  targetInTop5: boolean;
  /**
   * When target is outside the top 5: the two entries above, the target,
   * and the two entries below — each paired with their absolute rank.
   */
  contextRows?: { entry: AccountRankEntry; rank: number }[];
}

/** Full response shape returned by GET /api/account */
export interface AccountPageResponse {
  politician: Politician;
  rankings:   Record<ScoreKey, AccountRanking>;
  /** Overall rank by Knox Factor across all accounts — used in the hero. */
  overallRank: number;
  /** All processed posts for this account, newest first, no date filter. */
  allPosts:   RecentPost[];
  rangeLabel: string;
}

export interface RecentPost {
  postId:    string;
  caption:   string;
  views:     number;
  likes:     number;
  comments:  number;
  shares:    number;
  saves?:    number;
  summary?:  string;    // AI-generated summary from n8n / Gemini
  styles?:   string[];
  topic?:    string;
  coverJpeg?: string;
  videoMp4?:  string;
  postUrl?:   string;
  postDate?:  string;
}

/** Full post record used by the PostsTable section. */
export interface PostRecord {
  postId:          string;
  profile:         string;
  politicianName:  string;
  partyKey:        import('@/theme/colors').PartyKey;
  caption:         string;
  videoSummary:    string;
  coverJpeg:       string;
  videoMp4:        string;
  postUrl:         string;
  postDate:        string;
  styles:          string[];
  topics?:         string[];
  views:           number;
  likes:           number;
  comments:        number;
  shares:          number;
  saves:           number;
  accountFollowers: number;   // for virality = views / followers ratio
}

/**
 * Statistical distribution benchmarks for a metric across the full post dataset.
 * Used to render box-and-whisker plots per post.
 */
export interface MetricBenchmark {
  min:    number;
  p25:    number;
  median: number;
  mean:   number;
  p75:    number;
  max:    number;
}

/** Weekly briefing generated by Gemini — returned by /api/brief (legacy on-demand) */
export interface BriefResponse {
  narrative: string;
  insights:  Array<{ headline: string; body: string }>;
}

/** Row shape as stored in ariadne_tiktok_demo.brief by n8n */
export interface StoredBrief {
  briefDate:             string;   // 'yyyy-mm-dd'
  briefDailySummary:     string;
  briefWeeklySummary:    string;
  topNarrativesThisWeek: Array<{ headline: string; body: string }>;
}

/** Response from GET /api/briefs */
export interface BriefsApiResponse {
  brief:     StoredBrief;
  isToday:   boolean;   // false if the latest row is from a previous day
}

export interface PostBenchmarks {
  views:      MetricBenchmark;
  engagement: MetricBenchmark;  // (likes + comments + saves + shares) / views × 100
}

/**
 * Account type — raw DB values from accountType.name (snake_case).
 * These are the canonical values returned by inferAccountType() and stored
 * on every Politician record. 'council' and 'other' are fallback types used
 * when no DB match is found and regex inference is applied instead.
 */
export type AccountType =
  | 'member_of_parliament'
  | 'political_party'
  | 'party_leader'
  | 'prime_minister'
  | 'cabinet_minister'
  | 'shadow_cabinet_minister'
  | 'council'
  | 'other';

export interface Politician {
  id: string;
  name: string;
  handle: string;           // e.g. "@rishisunak"
  role: string;             // e.g. "MP, Richmond"
  partyKey: PartyKey;
  partyLabel: string;       // human-readable party name
  country: string;          // ISO-style short e.g. "UK"
  avatarInitials: string;   // two-letter fallback
  avatarUrl?: string;       // signed GCS photo URL from account.avatar
  accountTypes?: AccountType[];  // all types — a politician may have several (e.g. party_leader + member_of_parliament)
  totals: {
    posts:          number;
    followers:      number;
    followerChange: number | null;  // daily delta — positive = growth
    likes:          number;
    /** Lifetime view count across all the account's posts, sourced from accountMetrics.totalViews. */
    views:          number;
    views24h:       number;
    likesToday:     number;
    commentsToday:  number;
    savesToday:     number;
    postsToday:     number;
    postsThisWeek:  number;
    /** Posts within the currently selected range — matches the active API ?range= param. */
    postsInRange:   number;
    /** Range-specific aggregates from the post table — zero when no posts exist in range. */
    viewsInRange:    number;
    likesInRange:    number;
    commentsInRange: number;
    savesInRange:    number;
    sharesInRange:   number;
  };
  scores: TopTrumpScores;
  recentPosts?: RecentPost[];
}
